# -*- coding: utf-8 -*-
"""quad-stream-ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4i4jHPQ48MBxj8H4aI_DQOSOYQiV64q

Installations
"""

!pip install -q --upgrade pip

"""Avaliable GPU"""

!nvidia-smi

"""Git Repository"""

!git clone https://github.com/Deeptrust-us/deepfake_audio.git

!pip install -r /content/deepfake_audio/requirements.txt

!apt-get update
!apt-get install -y zstd

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/deepfake_audio

!git checkout main

"""Dataset import"""

from google.colab import drive
drive.mount('/content/drive')

!cp "/content/drive/MyDrive/dataset-quad/dataset.tar.zst" .

!tar -I zstd -xf /content/deepfake_audio/dataset.tar.zst -C /content/

!mv /content/content/deepfake_audio/dataset /content/deepfake_audio

!rm -r /content/content/

!rm -r /content/deepfake_audio/dataset/audio

ls -R -1 /content/deepfake_audio/dataset | wc -l

!du -sh /content/deepfake_audio/dataset/

# Point to your dataset in Drive
DATASET_DIR = "/content/deepfake_audio/dataset"
LABELS = f"{DATASET_DIR}/labels.json"

import os, json
print("labels.json exists:", os.path.exists(LABELS))

"""Precompute features"""

!lscpu

!nvidia-smi

!python scripts/preprocess_audio.py --dataset-root /content/deepfake_audio/dataset \
  --segment-mode random_one --seed 42 \
  --num-workers 8 --torch-threads 1

!git fetch
!git pull origin main

# remove old labels.json
!rm /content/deepfake_audio/dataset/labels.json

# move new split labels into the dataset folder
!mv /content/deepfake_audio/split_2/labels_test.json \
   /content/deepfake_audio  /split_2/labels_train.json \
   /content/deepfake_audio/split_2/labels_val.json \
   /content/deepfake_audio/dataset/

"""Train Model"""

!python scripts/train.py --config config/config.yaml

!cp -r /content/deepfake_audio/checkpoints /content/drive/MyDrive/dataset-quad/

!cp -r /content/drive/MyDrive/dataset-quad/checkpoints-split1-5epoch /content/deepfake_audio/checkpoints/
!cp -r /content/drive/MyDrive/dataset-quad/checkpoints-split1-5epoch /content/deepfake_audio/checkpoints/

!cp -r /content/drive/MyDrive/dataset-quad/splits/split_1 /content/drive/MyDrive/dataset-quad/splits/split_2 /content/deepfake_audio/dataset/

!python scripts/evaluate.py --config config/config.yaml --checkpoint checkpoints/best_model.pth --split test --trust-checkpoint

!python scripts/evaluate.py --config config/config.yaml --checkpoint checkpoints/best_model.pth --split test --trust-checkpoint

"""cross-domain test

testing train in split 1
"""

!sed -i 's|dataset/split_[0-9]\+/labels_|dataset/split_1/labels_|g' /content/deepfake_audio/config/config.yaml
!head -n 13 /content/deepfake_audio/config/config.yaml

!python scripts/evaluate.py --config config/config.yaml --checkpoint checkpoints/checkpoints-split1-5epoch/best_model.pth --split test

!sed -i 's|dataset/split_[0-9]\+/labels_|dataset/split_2/labels_|g' /content/deepfake_audio/config/config.yaml
!head -n 13 /content/deepfake_audio/config/config.yaml

!python scripts/evaluate.py --config config/config.yaml --checkpoint checkpoints/checkpoints-split1-5epoch/best_model.pth --split test

"""testing train in split 2"""

!sed -i 's|dataset/split_[0-9]\+/labels_|dataset/split_1/labels_|g' /content/deepfake_audio/config/config.yaml
!head -n 13 /content/deepfake_audio/config/config.yaml

!python scripts/evaluate.py --config config/config.yaml --checkpoint checkpoints/checkpoints-split2-6epoch/best_model.pth --split test

!sed -i 's|dataset/split_[0-9]\+/labels_|dataset/split_2/labels_|g' /content/deepfake_audio/config/config.yaml
!head -n 13 /content/deepfake_audio/config/config.yaml

!python scripts/evaluate.py --config config/config.yaml --checkpoint checkpoints/checkpoints-split2-6epoch/best_model.pth --split test

!cp "/content/drive/MyDrive/dataset-quad/dataset.tar.zst" .